---

# ============================================================================================ #
# role: dots
# -------------------------------------------------------------------------------------------- #

dots_folders:
  - "Development/Projects"
  - "Development/Notes"
  - "Development/Scratch"
  - "Development/Logs"
  - "Development/Build"

dots_post_processing:
  - name: "Install `bat` themes"
    cmd: "{{ bat_exec }} cache --build"

dots_templates:
  - name: "atuin.zsh.j2"
    dest: "{{ zsh_rcd_dir }}"
  - name: "op-ssh.bash.j2"
    dest: "{{ ansible_facts['user_dir'] }}/.local/share"


# ============================================================================================ #
# role: fonts
# -------------------------------------------------------------------------------------------- #

fonts_to_install:
  - "JetBrainsMono"
  - "SourceCodePro"


# ============================================================================================ #
# role: git
# -------------------------------------------------------------------------------------------- #

git_ssh_authorized_keys_match: "[?contains(title,'{{ ansible_facts['user_id'] }}')&&!contains(title,'{{ ansible_facts['hostname'] }}')]"
git_repos_as_worktrees: true
git_repos_path: "{{ ansible_facts['user_dir'] }}/Development/Projects"
git_repos:
  - url: "ssh://git@github.com/bradleyfrank/dotfiles.git"
  - url: "ssh://git@github.com/bradleyfrank/ansible.git"
  - url: "ssh://git@github.com/bradleyfrank/home-servers.git"
  - url: "ssh://git@github.com/bradleyfrank/plexport.git"
  - url: "ssh://git@github.com/bradleyfrank/chatgpt.git"
  - url: "ssh://git@github.com/bradleyfrank/util-containers.git"
  - url: "ssh://git@github.com/bradleyfrank/cliday.git"
    branch: "gh-pages"


# ============================================================================================ #
# role: pkgs
# -------------------------------------------------------------------------------------------- #

pkgs_binaries:
  - name: "cht"
    url: "https://raw.githubusercontent.com/chubin/cheat.sh/master/share/cht.sh.txt"
  - name: "extract"
    url: "https://raw.githubusercontent.com/xvoland/Extract/master/extract.sh"

pkgs_flatpak_remotes:
  - name: "flathub"
    url: "https://flathub.org/repo/flathub.flatpakrepo"
  - name: "elementary"
    url: "https://flatpak.elementary.io/repo.flatpakrepo"

pkgs_flatpak_packages:
  flathub:
    - "app.drey.EarTag"
    - "app.drey.Warp"
    - "com.felipekinoshita.Wildcard"
    - "com.github.avojak.warble"
    - "com.github.fabiocolacio.marker"
    - "com.github.geigi.cozy"
    - "com.github.huluti.Curtail"
    - "com.github.johnfactotum.Foliate"
    - "com.github.junrrein.PDFSlicer"
    - "com.github.liferooter.textpieces"
    - "com.github.marktext.marktext"
    - "com.github.rajsolai.textsnatcher"
    - "com.makemkv.MakeMKV"
    - "com.plexamp.Plexamp"
    - "com.spotify.Client"
    - "fr.romainvigier.MetadataCleaner"
    - "io.bassi.Amberol"
    - "io.github.alainm23.planify"
    - "io.github.diegoivan.pdf_metadata_editor"
    - "io.github.seadve.Kooha"
    - "io.gitlab.news_flash.NewsFlash"
    - "io.posidon.Paper"
    - "nl.g4d.Girens"
    - "org.gnome.gitlab.somas.Apostrophe"
    - "org.nickvision.tagger"
    - "org.ppsspp.PPSSPP"
    - "org.signal.Signal"
    - "re.sonny.Junction"
    - "re.sonny.Tangram"
    - "sh.cider.Cider"
    - "tv.plex.PlexDesktop"
    - "us.zoom.Zoom"
  elementary:
    - "com.github.phase1geo.annotator"


# ============================================================================================ #
# role: system
# -------------------------------------------------------------------------------------------- #

system_linux_dconf_defaults:
  - path: "/org/gnome"
    keys:
      calendar/follow-night-light: "false"
      shell/disable-user-extensions: "false"
      system/location/enabled: "true"
      settings-daemon/plugins/color/night-light-enabled: "true"
      settings-daemon/plugins/color/night-light-schedule-automatic: "true"
      terminal/legacy/profiles:/default: "'1846491d-b417-5d9b-a8ca-04fdec4403bf'"
      terminal/legacy/profiles:/list: "['1846491d-b417-5d9b-a8ca-04fdec4403bf']"
  - path: "/org/gnome/nautilus"
    keys:
      list-view/default-visible-columns: "['name', 'size', 'type', 'date_modified', 'starred']"
      list-view/default-zoom-level: "'small'"
      list-view/use-tree-view: "true"
      preferences/default-folder-viewer: "'list-view'"
      preferences/search-filter-time-type: "'last_modified'"
      preferences/show-create-link : "true"
      preferences/show-delete-permanently: "true"
  - path: "/org/gnome/gedit/preferences"
    keys:
      editor/auto-indent: "true"
      editor/auto-save: "true"
      editor/background-pattern: "'none'"
      editor/bracket-matching: "true"
      editor/display-line-numbers: "true"
      editor/display-overview-map: "true"
      editor/display-right-margin: "true"
      editor/editor-font: "'SauceCodePro Nerd Font 11'"
      editor/highlight-current-line: "true"
      editor/insert-spaces: "true"
      editor/right-margin-position: "uint32 100"
      editor/scheme: "'solarized-light'"
      editor/tabs-size: "uint32 2"
      editor/use-default-font: "false"
      editor/wrap-last-split-mode: "'word'"
      ui/show-tabs-mode: "'auto'"
      ui/side-panel-visible: "false"
  - path: "/org/gnome/terminal/legacy/profiles:/:1846491d-b417-5d9b-a8ca-04fdec4403bf"
    keys:
      audible-bell: "false"
      background-color: "'rgb(253,246,227)'"
      bold-is-bright: "false"
      cursor-colors-set: "false"
      font: "'SauceCodePro Nerd Font 12'"
      foreground-color: "'rgb(101,123,131)'"
      highlight-colors-set: "false"
      palette: "['rgb(7,54,66)', 'rgb(220,50,47)', 'rgb(133,153,0)', 'rgb(181,137,0)', 'rgb(38,139,210)',
        'rgb(211,54,130)', 'rgb(42,161,152)', 'rgb(238,232,213)', 'rgb(0,43,54)', 'rgb(203,75,22)',
        'rgb(88,110,117)', 'rgb(101,123,131)', 'rgb(131,148,150)', 'rgb(108,113,196)',
        'rgb(147,161,161)', 'rgb(253,246,227)']"
      scroll-on-output: "true"
      scrollback-unlimited: "true"
      use-system-font: "false"
      use-theme-colors: "false"
      visible-name: "'Solarized-Light-Profile'"
  - path: "/org/gnome/desktop"
    keys:
      datetime/automatic-timezone: "true"
      input-sources/current: "uint32 0"
      input-sources/sources: "[('xkb', 'us')]"
      input-sources/xkb-options: "['ctrl:nocaps']"
      interface/clock-format: "'12h'"
      interface/clock-show-date: "true"
      interface/clock-show-seconds: "false"
      interface/clock-show-weekday: "true"
      interface/enable-animations: "false"
      interface/show-battery-percentage: "false"
      media-handling/autorun-never: "true"
      media-handling/autorun-x-content-ignore: "[\
        'x-content/audio-cdda',
        'x-content/video-dvd',
        'x-content/audio-player',
        'x-content/image-dcf',
        'x-content/unix-software']"
      peripherals/keyboard/numlock-state: "true"
      peripherals/mouse/natural-scroll: "false"
      peripherals/touchpad/tap-to-click: "true"
      peripherals/touchpad/two-finger-scrolling-enabled: "true"
      privacy/remove-old-temp-files: "true"
      privacy/remove-old-trash-files: "true"

system_linux_dracut_settings:
  - desc: "Enable bluetooth keyboard at boot"
    line: "add_dracutmodules+=' bluetooth '"
    path: "/etc/dracut.conf.d/ble.conf"


# ============================================================================================ #
# role: tmux
# -------------------------------------------------------------------------------------------- #

tmux_profiles:
  - "tmux"
  - "popup"
  - "server"

tmux_plugins:
  - name: "tmux-resurrect"
    repo: "https://github.com/tmux-plugins/tmux-resurrect.git"
    exec: "resurrect.tmux"


# ============================================================================================ #
# role: vim
# -------------------------------------------------------------------------------------------- #

vim_extensions:
  - name: "vim-airline"
    repo: "https://github.com/vim-airline/vim-airline.git"
  - name: "vim-airline-themes"
    repo: "https://github.com/vim-airline/vim-airline-themes.git"
  - name: "vim-gitgutter"
    version: "main"
    repo: "https://github.com/airblade/vim-gitgutter.git"
  - name: "vim-indent-guides"
    repo: "https://github.com/preservim/vim-indent-guides.git"
  - name: "vim-terraform"
    repo: "https://github.com/hashivim/vim-terraform.git"
  - name: "vim-solarized8"
    repo: "https://github.com/lifepillar/vim-solarized8.git"
  - name: "vim-jinja2-syntax"
    repo: "https://github.com/Glench/Vim-Jinja2-Syntax.git"
  - name: "fzf.vim"
    repo: "https://github.com/junegunn/fzf.vim.git"
  - name: "vim-fugitive"
    repo: "https://github.com/tpope/vim-fugitive.git"
  - name: "vim-searchsavvy"
    repo: "https://github.com/idbrii/vim-searchsavvy.git"
  - name: "vim-css-color"
    repo: "https://github.com/ap/vim-css-color.git"
  - name: "vim-markdown"
    repo: "https://github.com/preservim/vim-markdown.git"


# ============================================================================================ #
# role: zsh
# -------------------------------------------------------------------------------------------- #

zsh_rcd_dir: "{{ ansible_facts['user_dir'] }}/.local/share/zsh/rc.d"

zsh_completions:
  - name: "cht"
    command: "curl -L https://cheat.sh/:zsh"
  - name: "nb"
    command: "curl -L https://raw.githubusercontent.com/xwmx/nb/master/etc/nb-completion.zsh"

zsh_plugins:
  - name: "zpy"
    repo: "https://github.com/AndydeCleyre/zpy.git"
    source: "zpy.plugin.zsh"
  - name: "zman"
    repo: "https://github.com/mattmc3/zman"
    source: "zman.zsh"
  - name: "fzf-tab"
    repo: "https://github.com/Aloxaf/fzf-tab"
    source: "fzf-tab.plugin.zsh"
  - name: "zsh-vi-mode"
    repo: "https://github.com/jeffreytse/zsh-vi-mode.git"
    source: "zsh-vi-mode.plugin.zsh"
