---

git_ssh_authorized_keys_search: "[?contains(title,'bfrank')]"
git_repos_as_worktrees: true
git_repos_path: "{{ ansible_facts['user_dir'] }}/Development/Projects"
git_repos:
  - url: "ssh://git@github.com/bradleyfrank/dotfiles.git"
  - url: "ssh://git@github.com/bradleyfrank/ansible.git"
  - url: "ssh://git@github.com/bradleyfrank/notes-etc.git"
  - url: "ssh://git@github.com/bradleyfrank/home-servers.git"
  - url: "ssh://git@github.com/bradleyfrank/plexex.git"
  - url: "ssh://git@github.com/bradleyfrank/chatgpt.git"
  - url: "ssh://git@github.com/bradleyfrank/util-containers.git"
  - url: "ssh://git@github.com/bradleyfrank/cliday.git"
    branch: "gh-pages"

zsh_rcd: "{{ ansible_facts['user_dir'] }}/.local/share/zsh/rc.d"

dots_post_processing:
  - name: "Install `bat` themes"
    cmd: "{{ bat_exec }} cache --build"

pkgs_binaries:
  - name: "cht"
    url: "https://raw.githubusercontent.com/chubin/cheat.sh/master/share/cht.sh.txt"
  - name: "extract"
    url: "https://raw.githubusercontent.com/xvoland/Extract/master/extract.sh"

fonts_to_install:
  - JetBrainsMono
  - SourceCodePro

git_reference_repos:
  - owner: dylanaraps
    repo: pure-bash-bible
    branch: master
    file: README.md
  - owner: jlevy
    repo: the-art-of-command-line
    branch: master
    file: README.md
  - owner: majamin
    repo: oneliners.txt
    branch: master
    file: oneliners.txt
  - owner: gto76
    repo: python-cheatsheet
    branch: main
    file: README.md

tmux_profiles:
  - tmux
  - popup

krew_plugins:
  - cert-manager
  - deprecations
  - get-all
  - neat
  - stern

vim_extensions:
  - name: vim-airline
    repo: https://github.com/vim-airline/vim-airline.git
  - name: vim-airline-themes
    repo: https://github.com/vim-airline/vim-airline-themes.git
  - name: vim-gitgutter
    version: main
    repo: https://github.com/airblade/vim-gitgutter.git
  - name: indentLine
    repo: https://github.com/Yggdroot/indentLine.git
  - name: vim-terraform
    repo: https://github.com/hashivim/vim-terraform.git
  - name: vim-solarized8
    repo: https://github.com/lifepillar/vim-solarized8.git
  - name: vim-jinja2-syntax
    repo: https://github.com/Glench/Vim-Jinja2-Syntax.git
  - name: fzf.vim
    repo: https://github.com/junegunn/fzf.vim.git
  - name: vim-fugitive
    repo: https://github.com/tpope/vim-fugitive.git
  - name: vim-searchsavvy
    repo: https://github.com/idbrii/vim-searchsavvy.git
  - name: vim-css-color
    repo: https://github.com/ap/vim-css-color.git

zsh_completions:
  - name: cht
    command: curl https://cheat.sh/:zsh

zsh_plugins:
  - name: zpy
    repo: https://github.com/AndydeCleyre/zpy.git
    source: zpy.plugin.zsh
  - name: zman
    repo: https://github.com/mattmc3/zman
    source: zman.zsh
  - name: fzf-tab
    repo: https://github.com/Aloxaf/fzf-tab
    source: fzf-tab.plugin.zsh
  - name: zsh-vi-mode
    repo: https://github.com/jeffreytse/zsh-vi-mode.git
    source: zsh-vi-mode.plugin.zsh
