---
# vars file for packages

base_packages:
  - abcde
  - audacious
  - bat
  - borgbackup
  - calibre
  - celluloid
  - code
  - dictd
  - docker
  - fail2ban
  - fdupes
  - ffmpeg
  - figlet
  - foliate
  - fwupd
  - fzf
  - gedit-autotab-git
  - gedit-duplicate-line
  - gedit-markdownpreview-git
  - gedit-scroll-past
  - gedit-solarized-git
  - gedit-strip-whitespace
  - ghostscript
  - ghostwriter
  - github-cli
  - glances
  - gnome-shell-extensions
  - gnome-tweaks
  - gnote
  - gpaste
  - htop
  - iftop
  - keepassxc
  - keychain
  - kubectl
  - libgnome-keyring
  - libreoffice
  - meld
  - mkvtoolnix-cli
  - mkvtoolnix-gui
  - most
  - mpv
  - msmtp
  - mtr
  - ncdu
  - neofetch
  - nextcloud-client
  - nmap
  - noto-fonts-emoji
  - openconnect
  - p7zip
  - perf
  - picard
  - pidgin
  - python-pip
  - python3
  - remmina
  - reptyr
  - ruby
  - seahorse
  - shellcheck
  - signal-desktop
  - solaar
  - stow
  - strace
  - system-config-printer
  - thunderbird
  - timeshift
  - tlp
  - tmux
  - torbrowser-launcher
  - transmission-gtk
  - trash-cli
  - tree
  - vim
  - vlc
  - wget
  - xz
  - yay
  - youtube-dl
  - zsh

aur_packages:
  - 1password
  - google-chrome
  - makemkv
  - makemkv-libaacs
  - nautilus-nextcloud
  - newsflash
  - par
  - plexamp-appimage
  - spotify
  - toilet
