---
# vars file for packages

base_packages:
  - bind-utils
  - borgbackup
  - cifs-utils
  - chrony
  - device-mapper-persistent-data
  - fail2ban
  - fdupes
  - figlet
  - gh
  - git
  - glances
  - htop
  - iftop
  - keychain
  - kubectl
  - libvirt-client
  - lvm2
  - mdadm
  - msmtp
  - mtr
  - ncdu
  - neofetch
  - nmap
  - p7zip
  - p7zip-plugins
  - pciutils
  - perf
  - podman
  - reptyr
  - ruby
  - setools
  - stow
  - strace
  - tmux
  - tree
  - unzip
  - vim
  - wget
  - xz
  - youtube-dl
  - yum-utils
  - zsh
  - zsh-syntax-highlighting
