---
# vars file for packages

taps:
  - homebrew/bundle
  - homebrew/cask
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - homebrew/core


base_packages:
  - bash
  - bash-completion@2
  - bat
  - bcal
  - cabextract
  - coreutils
  - dict
  - findutils
  - fdupes
  - flac
  - fzf
  - gawk
  - gh
  - ghostscript
  - git
  - glances
  - glow
  - gnu-sed
  - gnu-tar
  - gnu-which
  - grep
  - gzip
  - hexyl
  - iftop
  - kpcli
  - keychain
  - kubectx
  - lame
  - less
  - markdown
  - mas
  - mtr
  - most
  - ncdu
  - neofetch
  - nmap
  - p7zip
  - par
  - prettyping
  - python
  - rename
  - rpm2cpio
  - rsync
  - shellcheck
  - shellharden
  - shfmt
  - ssh-copy-id
  - stow
  - tmux
  - tree
  - vim
  - watch
  - wget
  - yamllint
  - yq
  - zsh
  - zsh-syntax-highlighting

home_packages:
  - awscli
  - eye-d3
  - ffsend
  - jq
  - stern
  - youtube-dl


base_casks:
  - anylist
  - appcleaner
  - balenaetcher
  - chromium
  - docker
  - fedora-media-writer
  - firefox
  - font-clear-sans
  - font-source-code-pro
  - google-chrome
  - google-drive-file-stream
  - iina
  - keepassxc
  - keepingyouawake
  - logitech-options
  - macdown
  - meld
  - transmission
  - visual-studio-code
  - vivaldi
  - vlc
  - xquartz

home_casks:
  - 1password
  - bartender
  - calibre
  - fantastical
  - google-cloud-sdk
  - istat-menus
  - musicbrainz-picard
  - plexamp
  - signal
  - sony-ps4-remote-play
  - spotify
  - stay
  - textmate
  - transmit
  - zoomus

work_casks:
  - bbedit
  - dozer
  - jumpcut
  - menumeters
  - rectangle


home_apps:
  - 407963104  # Pixelmator
  - 409183694  # Keynote
  - 409201541  # Pages
  - 409203825  # Numbers
  - 425424353  # The Unarchiver
  - 441258766  # Magnet
  - 568494494  # Pocket
  - 924726344  # Deliveries
  - 1176895641  # Spark Mail
  - 1179623856  # Pastebot
  - 1289378661  # Twitterific
  - 1320666476  # Wipr
  - 1449412482  # Reeder 4
