---
# vars file for packages

python_packages:
  - black
  - dns-lexicon
  - imgur_downloader
  - pip-autoremove
  - pip_upgrade_outdated
  - pycodestyle
  - pydf
  - pyflakes
  - pylint
  - tmuxp
  - tuir

vscode_extensions:
  - bitzl.vscode-puppet
  - bungcip.better-toml
  - davidanson.vscode-markdownlint
  - donjayamanne.githistory
  - haaaad.ansible
  - mhutchie.git-graph
  - mikestead.dotenv
  - ms-azuretools.vscode-docker
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - ms-python.python
  - ms-vscode-remote.remote-containers
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit
  - ms-vscode-remote.remote-wsl
  - ms-vscode-remote.vscode-remote-extensionpack
  - Remisa.shellman
  - rogalmic.bash-debug
  - samuelcolvin.jinjahtml
  - shd101wyy.markdown-preview-enhanced
  - timonwong.shellcheck
  - Tyriar.sort-lines
  - vortizhe.simple-ruby-erb