---
# tasks file for desktop

- name: Install firewalld rules
  vars:
    firewalld_zone: public
    firewalld_become: true
    firewalld_services:
      - cockpit
      - ssh
  include_role: firewalld
  tags:
    - security

- name: Load shared Linux tasks
  include_tasks: Linux.yml
