---
# tasks file for desktop

- name: Make zsh default for user
  user:
    name: "{{ ansible_env.USER }}"
    shell: "/usr/bin/zsh"
  become: true
  tags:
    - shell

- name: Make bash default for root
  user:
    name: root
    shell: /usr/bin/bash
  become: true
  tags:
    - root
    - shell

- name: Install root dotfiles
  copy:
    src: root/
    dest: /root/
    mode: 0644
  become: true
  tags:
    - root

- name: Import dconf settings
  shell: dconf load / < "{{ item }}"
  with_fileglob:
    - "conf/Linux/shared.dconf"
    - "conf/Linux/{{ ansible_distribution }}.dconf"
  when: "'gnome' in ansible_env.XDG_CURRENT_DESKTOP | lower"
  tags:
    - gnome_settings

- name: Secure OS settings
  import_role:
    name: dev-sec.os-hardening
  tags:
    - security

- name: Secure SSH settings
  import_role:
    name: dev-sec.ssh-hardening
  tags:
    - security