---
# tasks file for desktop

- name: Apply desktop settings
  include_tasks: "{{ desktop }}.yml"

- name: Make zsh default for user
  user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ usr_path }}/bin/zsh"
  become: true

- name: Make bash default for root
  user:
    name: 'root'
    shell: "{{ usr_path }}/bin/bash"
  become: true

- name: Install root bash_profile
  copy:
    src: 'root/bash_profile'
    dest: "{{ rootdir }}/.bash_profile"
  become: true

- name: Install root bashrc
  copy:
    src: 'root/bashrc'
    dest: "{{ rootdir }}/.bashrc"
  become: true