---
# tasks file for packages

- name: Install Manjaro packages
  pacman:
    name: "{{ base_packages | default([]) }}"
    state: present
    update_cache: true
  become: true
  tags:
    - packages

- name: Install Manjaro Gnome packages
  pacman:
    name: "{{ gnome_packages | default([]) }}"
    state: present
    update_cache: true
  become: true
  when: "'gnome' in ansible_env.XDG_CURRENT_DESKTOP | lower"
  tags:
    - packages

- name: Install Manjaro AUR packages
  kewlfft.aur:
    name: "{{ aur_packages | default([]) }}"
    use: yay
    state: present
  tags:
    - packages
