---
# tasks file for packages

- name: Install Homebrew taps
  homebrew_tap:
    name: "{{ taps }}"
  tags:
    - packages
    - taps

- name: Install Homebrew packages
  homebrew:
    name: "{{ packages }}"
  tags:
    - packages
    - formulas

- name: Install Homebrew casks
  homebrew_cask:
    name: "{{ casks }}"
    accept_external_apps: true
  tags:
    - packages
    - casks

- name: Check Mac App Store authentication status
  shell:
    cmd: mas account
  register: mas_account
  tags:
    - packages
    - apps

- name: Install Mac App Store apps
  command:
    cmd: "/usr/local/bin/mas install {{ item }}"
  loop: "{{ apps }}"
  when: mas_account.stdout == icloud_address
  tags:
    - packages
    - apps

- name: Install fonts
  copy:
    src: fonts/
    dest: "{{ ansible_env.HOME }}/Library/Fonts/"
    mode: 0644
  tags:
    - packages
    - fonts

- name: Install VSCode extensions
  command: "/usr/local/bin/code --install-extension {{ item }}"
  loop: "{{ vscode_extensions }}"
  tags:
    - packages
    - vscode
