---
# tasks file for packages

- name: Install Fedora packages
  dnf:
    name: "{{ base_packages | default([]) }}"
    state: present
    update_cache: true
    install_weak_deps: true
    autoremove: true
    autoclean: true
  become: true
  tags:
    - packages

- name: Install Fedora Gnome packages
  dnf:
    name: "{{ gnome_packages | default([]) }}"
    state: present
    update_cache: true
    install_weak_deps: true
  become: true
  when: "'gnome' in ansible_env.XDG_CURRENT_DESKTOP | lower"
  tags:
    - packages

- name: Install Fedora Flatpaks
  community.general.flatpak:
    name: "{{ item.name }}"
    state: present
    remote: "{{ item.remote }}"
  loop: "{{ flatpak_packages }}"
