---
# tasks file for packages

- name: Update apt cache
  apt:
    update_cache: true
  become: true
  when: "'Ubuntu' in ansible_distribution"

- name: Install OS packages
  package:
    name: "{{ base_packages | default([]) }}"
    state: present
  become: true
  tags:
    - packages

- name: Install Gnome packages
  package:
    name: "{{ gnome_packages | default([]) }}"
    state: present
  become: true
  when: "'gnome' in desktop | lower"
  tags:
    - packages

- name: Install fonts
  copy:
    src: fonts/
    dest: /usr/local/share/fonts/
    mode: 0644
  when: ansible_env.XDG_CURRENT_DESKTOP is defined
  become: true
  tags:
    - fonts
    - packages

- name: Refresh font list
  command: fc-cache -fv
  when: ansible_env.XDG_CURRENT_DESKTOP is defined
  become: true
  tags:
    - fonts
    - packages

- name: Install VSCode extensions
  command: "/usr/bin/code --install-extension {{ item }}"
  loop: "{{ vscode_extensions }}"
  when: desktop != 'none'
  tags:
    - packages
    - vscode
