---
# tasks file for packages

- name: Install OS packages
  become: true
  package:
    name: "{{ base_packages | default([]) }}"
    state: present
  tags:
    - packages

- name: Install Gnome packages
  package:
    name: "{{ gnome_packages | default([]) }}"
    state: present
  become: true
  when: "'gnome' in desktop | lower"
  tags:
    - packages


- name: Install home-only OS packages
  package:
    name: "{{ home_packages | default([]) }}"
    state: present
  become: true
  tags:
    - home_only
    - packages

- name: Install work-only OS packages
  package:
    name: "{{ work_packages | default([]) }}"
    state: present
  become: true
  tags:
    - work_only
    - packages


- name: Install Source Code Pro
  copy:
    src: SourceCodePro/
    dest: /usr/local/share/fonts/
  when: "ansible_distribution == 'Ubuntu'"
  become: true
  tags:
    - fonts
    - packages

- name: Refresh font list
  command: fc-cache -fv
  when: "ansible_distribution == 'Ubuntu'"
  become: true
  tags:
    - fonts
    - packages
