---
# tasks file for packages

- name: Load OS packages lists
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - packages

- name: Install packages for OS
  include_tasks: "{{ ansible_system }}.yml"
  tags:
    - packages

- name: Install VSCode extensions
  command: "{{ usr_path }}/bin/code --install-extension {{ item }}"
  loop: "{{ vscode_extensions }}"
  when: "'server' not in desktop | lower"
  tags:
    - packages
    - vscode

- name: Install Python packages
  pip:
    name: "{{ python_packages }}"
    extra_args: --user
  tags:
    - packages
    - python
