---
# tasks file for packages

- name: Load OS packages lists
  include_vars: "os/{{ ansible_distribution }}.yml"

- name: Install packages for OS
  include_tasks: "{{ ansible_distribution }}.yml"


- name: Install VSCode extensions
  command:
    cmd: "{{ vscode }} --install-extension --force {{ item }}"
  with_items: "{{ vscode_extensions }}"
  tags:
    - packages

- name: Install Python packages
  pip:
    name: "{{ python_packages }}"
    extra_args: --user
  tags:
    - packages