---
# tasks file for packages

- name: Install Ubuntu packages
  apt:
    name: "{{ base_packages | default([]) }}"
    state: present
    update_cache: true
    install_recommends: true
    autoremove: true
    autoclean: true
  become: true
  tags:
    - packages

- name: Install Ubuntu Gnome packages
  apt:
    name: "{{ gnome_packages | default([]) }}"
    state: present
    update_cache: true
    install_recommends: true
    autoremove: true
    autoclean: true
  become: true
  when: "'gnome' in desktop | lower"
  tags:
    - packages
