---
# tasks file for packages

- name: Load shared Linux tasks
  include_tasks: Linux.yml
  tags:
    - packages

- name: Download Source Code Pro
  get_url:
    url: https://github.com/adobe-fonts/source-code-pro/archive/2.030R-ro/1.050R-it.zip
    dest: "/tmp/source-code-pro.zip"
  tags:
    - fonts
    - packages

- name: Extract Source Code Pro
  unarchive:
    src: /tmp/source-code-pro.zip
    dest: /tmp/
    remote_src: true
  tags:
    - fonts
    - packages

- name: Install Source Code Pro
  copy:
    src: /tmp/source-code-pro-2.030R-ro-1.050R-it/OTF/
    dest: /usr/local/share/fonts/
    remote_src: true
  become: true
  tags:
    - fonts
    - packages

- name: Cleanup temp files
  file:
    path: /tmp/source-code-pro-2.030R-ro-1.050R-it
    state: absent
  tags:
    - fonts
    - packages

- name: Refresh font list
  shell: fc-cache -fv
  tags:
    - fonts
    - packages
