---
# tasks file for environment

- name: Make additional shells available
  blockinfile:
    path: /etc/shells
    block: |
      /usr/local/bin/bash
      /usr/local/bin/fish
      /usr/local/bin/zsh
  when: "{{ ansible_os_family }}" == 'Darwin'
  become: True

- name: Make zsh default
  user:
    name: "{{ ansible_env.USER }}"
    shell: "{{ shell }}"
  become: True

- name: Create ~/Development folder structure
  file:
    path: "{{ ansible_env.HOME }}/Development/{{ item }}"
    state: directory
    recurse: True
    mode: '0755'
  with_items: ['Projects', 'Build', 'Scratch']

- name: Configure ~/.ssh directory
  file:
    path: "{{ ansible_env.HOME }}/.ssh"
    state: directory
    mode: '0700'

- name: Install VSCode extensions
  command:
    cmd: "{{ vscode }} --install-extension {{ item }}"
  with_items: "{{ vscode_extensions }}"
  tags: packages

- name: Install Python packages
  pip:
    name: "{{ python_packages }}"
    extra_args: --user
  tags: packages