---
# tasks file for dotfiles

- name: Install shared dotfiles
  copy:
    src: "{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.path }}"
    mode: '0644'
  with_filetree: base/
  when: item.state == 'file'

- name: Install gitconfig
  template:
    src: gitconfig.j2
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    mode: '0755'

- name: Install tmux config
  template:
    src: tmux.conf.j2
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    mode: '0755'
