---
  # tasks file for dotfiles

- name: Load shared variables
  include_vars: shell/shared.yml

- name: Load distribution variables
  include_vars: "shell/{{ ansible_distribution }}.yml"

- name: Build zshrc
  template:
    src: "zshrc.j2"
    dest: "{{ ansible_env.HOME }}/.zshrc"
  vars:
    paths: "{{ shared_paths + distribution_paths | default([]) }}"
    manpaths: "{{ shared_manpaths + distribution_manpaths | default([]) }}"
    aliases: "{{ shared_aliases | combine(distribution_aliases) }}"
    functions: "{{ shared_functions | combine(distribution_functions) }}"