---
# tasks file for dotfiles

# Register gcloud first because it's used by vars/shell/shared.yml to source completion scripts.
- name: Register gcloud install location
  shell: gcloud info | sed -rn 's/^Installation Root:\s\[(.*)\]/\1/p'
  register: gcloud_base_dir

- name: Load shared shell variables
  include_vars: shell/shared.yml

- name: Load distribution shell variables
  include_vars: "shell/{{ ansible_system }}.yml"


- name: Create shellrc.d folders
  file:
    path: "{{ ansible_env.HOME }}/.{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - bashrc.d
    - zshrc.d


- name: Generate kubectl completions
  vars:
    kubectl_completion_path: "{{ ansible_env.HOME }}/.local/share/k8s/kubectl"
  shell:
    cmd: "{{ kubectl }} completion {{ item }} > {{ kubectl_completion_path }}.{{ item }}"
  loop:
    - zsh
    - bash

# p10k is not available as a Linux package so clone a release on all systems for consistency.
- name: Install powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_env.HOME }}/.local/share/powerlevel10k"
    depth: '1'
    version: v1.13.0


- name: Build zshrc
  template:
    src: zshrc.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"
    backup: true
  vars:
    shell_name: zsh
    evals: "{{ shared_evals + distribution_evals | default([]) }}"
    exports: "{{ shared_exports + distribution_exports | default([]) }}"
    paths: "{{ shared_paths + distribution_paths | default([]) }}"
    manpaths: "{{ shared_manpaths + distribution_manpaths | default([]) }}"
    aliases: "{{ shared_aliases | combine(distribution_aliases) }}"
    functions: "{{ shared_functions | combine(distribution_functions) }}"
    sources: "{{ shared_sources + distribution_sources | default([]) }}"

- name: Build bash_profile
  template:
    src: bash_profile.j2
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    backup: true
  vars:
    shell_name: bash
    exports: "{{ shared_exports + distribution_exports | default([]) }}"
    paths: "{{ shared_paths + distribution_paths | default([]) }}"
    manpaths: "{{ shared_manpaths + distribution_manpaths | default([]) }}"

- name: Build bashrc
  template:
    src: bashrc.j2
    dest: "{{ ansible_env.HOME }}/.bashrc"
    backup: true
  vars:
    shell_name: bash
    evals: "{{ shared_evals + distribution_evals | default([]) }}"
    aliases: "{{ shared_aliases | combine(distribution_aliases) }}"
    functions: "{{ shared_functions | combine(distribution_functions) }}"
    sources: "{{ shared_sources + distribution_sources | default([]) }}"
