---
# tasks file for dotfiles

- name: Load shared shell variables
  include_vars: shell/shared.yml

- name: Load distribution shell variables
  include_vars: "shell/{{ ansible_system }}.yml"


# p10k is not available as a Linux package so clone a release on all systems for consistency.
- name: Install powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_env.HOME }}/.local/share/powerlevel10k"
    depth: '1'
    version: v1.13.0


- name: Build zshrc
  template:
    src: zshrc.j2
    dest: "{{ ansible_env.HOME }}/.zshrc"
  vars:
    shell_name: zsh
    evals: "{{ shared_evals + distribution_evals | default([]) }}"
    exports: "{{ shared_exports + distribution_exports | default([]) }}"
    paths: "{{ shared_paths + distribution_paths | default([]) }}"
    manpaths: "{{ shared_manpaths + distribution_manpaths | default([]) }}"
    aliases: "{{ shared_aliases | combine(distribution_aliases) }}"
    functions: "{{ shared_functions | combine(distribution_functions) }}"
    sources: "{{ shared_sources + distribution_sources | default([]) }}"

- name: Build bash_profile
  template:
    src: bash_profile.j2
    dest: "{{ ansible_env.HOME }}/.bash_profile"
  vars:
    shell_name: bash
    exports: "{{ shared_exports + distribution_exports | default([]) }}"
    paths: "{{ shared_paths + distribution_paths | default([]) }}"
    manpaths: "{{ shared_manpaths + distribution_manpaths | default([]) }}"

- name: Build bashrc
  template:
    src: bashrc.j2
    dest: "{{ ansible_env.HOME }}/.bashrc"
  vars:
    shell_name: bash
    evals: "{{ shared_evals + distribution_evals | default([]) }}"
    aliases: "{{ shared_aliases | combine(distribution_aliases) }}"
    functions: "{{ shared_functions | combine(distribution_functions) }}"
    sources: "{{ shared_sources + distribution_sources | default([]) }}"
