---
# tasks file for dotfiles

- name: Create directory structure
  file:
    path: "{{ ansible_env.HOME }}/{{ item.path }}"
    state: directory
    mode: '0755'
  with_filetree: utils/
  when: item.state == 'directory'

- name: Install dotfiles
  copy:
    src: "{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.path }}"
    mode: '0644'
  with_filetree: utils/
  when: item.state == 'file'

- name: Install gitconfig
  template:
    src: gitconfig.j2
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    mode: '0755'

- name: Install tmux config
  template:
    src: tmux.conf.j2
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    mode: '0755'

- name: Generate kubectl completions
  vars:
    kubectl_completion_path: "{{ ansible_env.HOME }}/.local/share/k8s/kubectl"
  shell:
    cmd: "{{ kubectl }} completion {{ item }} > {{ kubectl_completion_path }}.{{ item }}"
  loop:
    - zsh
    - bash
