---
# tasks file for system

- name: Make zsh default for user
  user:
    name: "{{ ansible_env.USER }}"
    shell: "/usr/bin/zsh"
  become: true
  tags:
    - shell

- name: Make bash default for root
  user:
    name: root
    shell: /usr/bin/bash
  become: true
  tags:
    - root
    - shell

- name: Install root dotfiles
  copy:
    src: root/
    dest: /root/
    mode: 0644
  become: true
  tags:
    - root
    - shell

- name: Import dconf settings
  shell: dconf load / < "{{ item }}"
  with_fileglob:
    - "conf/Linux/shared.dconf"
    - "conf/Linux/{{ ansible_distribution }}.dconf"
  when: "'gnome' in ansible_env.XDG_CURRENT_DESKTOP | lower"
  tags:
    - gnome_settings

- name: Generate host keys
  command:
    cmd: ssh-keygen -A
    creates: /etc/ssh/ssh_host_*_key
  become: true

- name: Secure SSH settings
  import_role:
    name: devsec.hardening.ssh_hardening
  become: true
  when: "'Pop!_OS' not in ansible_distribution"
  tags:
    - security

- name: Secure SSH settings
  vars:
    sshd_path: /usr/sbin/sshd
    ssh_host_keys_dir: '/etc/ssh'
    sshd_service_name: ssh
    ssh_owner: root
    ssh_group: root
    ssh_selinux_packages:
      - policycoreutils-python
      - checkpolicy
    ssh_kerberos_support: true
    ssh_pam_support: true
    sshd_moduli_file: '/etc/ssh/moduli'
    sshd_disable_crypto_policy: false
  import_role:
    name: devsec.hardening.ssh_hardening
  become: true
  when: "'Pop!_OS' in ansible_distribution"
  tags:
    - security
