---
# vars file for dotfiles

font_dir: "{{ ansible_env.HOME }}/Library/Fonts"
usr_path: /usr/local
vscode_config: "{{ ansible_env.HOME }}/Library/Application Support/Code"
kubectl: /Applications/Docker.app/Contents/Resources/bin/kubectl
