---
# vars file for dotfiles

vim_extensions_dest: "{{ ansible_env.HOME }}/.vim/pack/default/start"

vim_extensions:
  - name: vim-airline
    repo: https://github.com/vim-airline/vim-airline.git
    version: v0.11
  - name: vim-airline-themes
    repo: https://github.com/vim-airline/vim-airline-themes.git
  - name: vim-gitgutter
    repo: https://github.com/airblade/vim-gitgutter.git

gists:
  - name: zshrc
    file: "{{ ansible_env.HOME }}/.zshrc"
    id: 5cbc46ffa9c930cf1214f7738761d55e
  - name: tmux
    file: "{{ ansible_env.HOME }}/.tmux.conf"
    id: 1e8da9260d3d24f2b6c237ceea116ccc