---
# vars file for dotfiles

keychain: eval "$(keychain --eval --ignore-missing --quiet --inherit any id_rsa id_develop id_home)"

distribution_exports:
  - CLICOLOR=1
  - HOMEBREW_PREFIX=/usr/local
  - HOMEBREW_CELLAR=/usr/local/Cellar
  - HOMEBREW_REPOSITORY=/usr/local/Homebrew
  - INFOPATH=/usr/local/share/info:"${INFOPATH:-}"

distribution_paths:
  - PATH="$PATH":~/Library/Python/3.8/bin
  - PATH="$PATH":/opt/X11/bin
  - PATH=/usr/local/opt/coreutils/libexec/gnubin:"$PATH"
  - PATH=/usr/local/opt/gnu-tar/libexec/gnubin:"$PATH"
  - PATH=/usr/local/opt/ed/libexec/gnubin:"$PATH"
  - PATH=/usr/local/opt/grep/libexec/gnubin:"$PATH"
  - PATH=/usr/local/opt/gnu-sed/libexec/gnubin:"$PATH"
  - PATH=/usr/local/opt/gawk/libexec/gnubin:"$PATH"
  - PATH=/usr/local/opt/findutils/libexec/gnubin:"$PATH"

distribution_manpaths:
  - MANPATH=/usr/local/opt/coreutils/libexec/gnuman:"$MANPATH"
  - MANPATH=/usr/local/opt/gnu-tar/libexec/gnuman:"$MANPATH"
  - MANPATH=/usr/local/opt/ed/libexec/gnuman:"$MANPATH"
  - MANPATH=/usr/local/opt/grep/libexec/gnuman:"$MANPATH"
  - MANPATH=/usr/local/opt/gnu-sed/libexec/gnuman:"$MANPATH"
  - MANPATH=/usr/local/opt/gawk/libexec/gnuman:"$MANPATH"
  - MANPATH=/usr/local/opt/findutils/libexec/gnuman:"$MANPATH"

distribution_aliases:
  steep: 'brew update ; brew upgrade ; brew cleanup ; brew doctor'

distribution_functions:
  ytdl-music: |-
    youtube-dl --format bestaudio --extract-audio --audio-format mp3 \
      --postprocessor-args "-strict experimental" "$1"

distribution_zsh_sources:
  - /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc
  - /usr/local/bin/google-cloud-sdk/completion.zsh.inc

distribution_bash_sources:
  - /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.bash.inc
  - /usr/local/bin/google-cloud-sdk/completion.bash.inc
