---
# vars file for dotfiles

shared_exports:
  - PATH
  - MANPATH
  - VISUAL=vim
  - EDITOR=vim
  - HSTR_CONFIG=monochromatic
  - GIT_PS1_SHOWDIRTYSTATE=true
  - GIT_PS1_SHOWSTASHSTATE=true
  - GIT_PS1_SHOWUNTRACKEDFILES=true
  - GIT_PS1_SHOWCOLORHINTS=true
  - GIT_PS1_SHOWUPSTREAM="verbose name"

shared_paths:
  - PATH=~/.local/bin:~/bin
  - PATH="$PATH":/usr/local/bin:/usr/local/sbin
  - PATH="$PATH":/usr/bin:/usr/sbin:/bin:/sbin

shared_manpaths:
  - MANPATH=~/.local/share/man
  - MANPATH=/usr/local/share/man:/usr/share/man:"$MANPATH"

shared_aliases:
  bw: 'bitwise --no-color'
  condense: 'grep -Erv "(^#|^$)"'
  e: 'extract'
  glances: 'glances --theme-white'
  groot: 'cd $(git rev-parse --show-toplevel)'
  isodate: 'date --iso-8601=seconds'
  l1: 'ls -1 --color --classify --human-readable'
  la: 'ls -la --color --classify --human-readable'
  lg: 'ls -Gg --color --classify --human-readable'
  ll: 'ls -l --color --classify --human-readable'
  lt: 'ls -1AS --color --classify --human-readable --group-directories-first --size'
  lsmnt: 'mount | column -t'
  rcp: 'rsync --info=progress2'
  pipi: 'python3 -m pip install --user'
  pipu: 'pip_upgrade_outdated -3 --user --verbose'
  pubip: 'dig myip.opendns.com @resolver1.opendns.com'
  tmuxl: 'tmux -f ~/.tmux.min.conf'

shared_functions:
  blackdiff: black --line-length 100 --diff "$@" | diff-so-fancy
  clint: docker-compose -f "$1" config --quiet
  crackpdf: qpdf --password="$1" --decrypt "$2" "${2%.*}"-decrypted.pdf
  diceware: keepassxc-cli diceware --words "${1:-5}" | tr " " "-"
  dotfiles: |-
    ansible-pull \
      --url https://github.com/bradleyfrank/dotfiles.git \
      --directory "$HOME"/.dotfiles \
      --tags dotfiles \
      --skip-tags {{ ansible_skip_tags | join(', ') }} \
      playbooks/{{ ansible_system | lower }}.yml
  decrypt: openssl enc -d -aes-256-cbc -in "$1" -out "$1.decrypted"
  encrypt: openssl enc -aes-256-cbc -salt -in "$1" -out "$1.encrypted"
  httptrace: curl -s -L -D - "$1" -o /dev/null -w "%{url_effective}\n"
  mkpasswd: keepassxc-cli generate -L "${1:-16}" -lUn --exclude-similar
  pylinter: |-
    blackdiff "$@"
    pylint "$@"
    pycodestyle "$@"
  sshgen: |-
    local comment password keyfile
    comment="$(id -un)@$(uname -n) on $(date --iso-8601=minute)"
    password="$(keepassxc-cli diceware --words 5 | tr ' ' '-')"
    keyfile="$HOME"/.ssh/id_"${1:-rsa}"
    [[ -e "$keyfile" ]] && keyfile="$HOME"/.ssh/id_"$(date +%s)"
    ssh-keygen -q -t rsa -b 4096 -N "$password" -C "$comment" -f "$keyfile"
    echo "$keyfile : $password"
  tardir: tar -czf "${1%/}".tar.gz "$1"
  cheat: curl -s "cheat.sh/$1?style=vs"
  ytdl-video: |-
    youtube-dl \
    --format "bestvideo+bestaudio[ext=m4a]/bestvideo+bestaudio/best" \
    --merge-output-format mp4 \
    -o "%(title)s.%(ext)s" "$1"

shared_zsh_sources:
  - ~/.local/share/git/git-prompt.sh
  - "{{ usr_path }}/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"

shared_bash_sources:
  - ~/.local/share/git/git-prompt.sh
