workspaces = true
show_preview = true
enter_accept = true
keymap_mode = "vim-insert"
stats.common_subcommands=["apt","dnf","docker","git","ip","kubectl","nix","nmcli","npm","podman","systemctl","tmux","nb"]
stats.ignored_commands = ["cd","ls","ll","vim","echo"]
