---
# tasks file for repositories

- name: Install gpg keys
  rpm_key:
    key: "{{ item.gpgkey }}"
  loop: "{{ repos }}"
  become: true

- name: Install repositories
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl | default(omit) }}"
    metalink: "{{ item.metalink | default(omit) }}"
    includepkgs: "{{ item.includepkgs | default('') }}"
    gpgcheck: "{{ item.gpgcheck | default(true) }}"
    gpgkey: "{{ item.gpgkey }}"
    repo_gpgcheck: "{{ item.repo_gpgcheck | default(false) }}"
    skip_if_unavailable: "{{ item.skip_if_unavailable | default(true) }}"
  loop: "{{ repos }}"
  become: true
