---
# tasks file for repositories

- name: Install gpg keys
  apt_key:
    url: "{{ item.key | default(omit) }}"
    keyring: "{{ item.keyring | default(omit) }}"
    id: "{{ item.id | default(omit) }}"
    keyserver: "{{ item.keyserver | default(omit) }}"
  loop: "{{ repos }}"
  become: true

- name: Install repositories
  apt_repository:
    repo: "{{ item.repo }}"
    filename: "{{ item.name }}"
  loop: "{{ repos }}"
  become: true

- name: Remove snapd
  apt:
    name:
      - gnome-software-plugin-snap
      - snapd
    state: absent
    purge: true
    autoremove: true
  become: true

- name: Block snap packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - snap
    - snapd
  become: true
