---

pkgs_apt_packages:
  cli:
    - abcde
    - apt-file
    - bash-completion
    - bat
    - bcal
    - borgbackup
    - diceware
    - dictd
    - duf
    - fd-find
    - fdupes
    - ffmpeg
    - figlet
    - fwupd
    - fzf
    - gh
    - ghostscript
    - glances
    - gron
    - htop
    - httpie
    - iftop
    - inxi
    - jq
    - keychain
    - libmp4-info-perl
    - libvirt-clients
    - mkvtoolnix
    - most
    - msmtp
    - mtr
    - ncdu
    - neofetch
    - nmap
    - p7zip-*
    - par
    - perf-tools-unstable
    - pdfgrep
    - podman
    - pwgen
    - python3
    - python3-dev
    - python3-pip
    - ripgrep
    - ruby
    - shellcheck
    - ssh
    - stow
    - strace
    - tidy
    - tlp
    - tmux
    - toilet
    - trash-cli
    - tree
    - vim
    - wget
    - xdelta
    - xsel
    - xz-utils
    - yt-dlp
    - zsh
    - zsh-autosuggestions
    - zsh-syntax-highlighting
  gui:
    - 1password
    - alacritty
    - asciinema
    - audacious
    - calibre
    - code
    - drawing
    - flatpak
    - fonts-noto-color-emoji
    - ghostwriter
    - google-chrome-stable
    - keepassxc
    - kitty
    - libreoffice
    - makemkv-bin
    - makemkv-oss
    - nextcloud-client
    - nextcloud-client-nautilus
    - picard
    - remmina
    - shutter
    - solaar
    - system-config-printer
    - timeshift
    - torbrowser-launcher
    - vlc
  gnome:
    - celluloid
    - geary
    - gedit-plugin-code-comment
    - gedit-plugin-color-picker
    - gedit-plugin-git
    - gedit-plugin-join-lines
    - gedit-plugin-multi-edit
    - gnome-characters
    - gnome-connections
    - gnome-games-app
    - gnome-keyring
    - gnome-shell-extension-manager
    - gnome-shell-extensions
    - gnome-shell-extensions-gpaste
    - gnome-sushi
    - gnome-tweaks
    - gnote
    - gpaste*
    - gthumb
    - hydrapaper
    - meld
    - mpv
    - transmission-gtk

brew_packages:
  - eza
  - glow
  - yq
