---

pkgs_apt_repos:
  - name: 1password
    repo: >
      deb [arch=amd64 signed-by=/usr/share/keyrings/1password-archive-keyring.gpg]
      https://downloads.1password.com/linux/debian/amd64 stable main
    key: https://onepassword.s3.amazonaws.com/linux/keys/1password.asc
    keyring: /usr/share/keyrings/1password-archive-keyring.gpg

  - name: google-chrome
    repo: deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main
    key: https://dl.google.com/linux/linux_signing_key.pub

  - name: gh-cli
    repo: >
      deb [arch=amd64 signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg]
      https://cli.github.com/packages stable main
    key: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    keyring: /usr/share/keyrings/githubcli-archive-keyring.gpg

  - name: charm
    repo: deb [trusted=yes] https://repo.charm.sh/apt/ /
    key: https://apt.fury.io/charmcli/gpg.key
    keyring: /usr/share/keyrings/charmcli.gpg
