---

- name: MacOS Workstation
  hosts: localhost
  vars:
    desktop: "{{ ansible_distribution }}"
    usr_path: /usr/local
    vscode_config: "{{ ansible_env.HOME }}/Library/Application Support/Code"
    kubectl: /Applications/Docker.app/Contents/Resources/bin/kubectl
  roles:
    - packages
    - dotfiles
    - system
