---

- name: MacOS Workstation
  hosts: localhost
  vars:
    desktop: "{{ ansible_distribution }}"
    usr_path: '/usr/local'
    vscode_config: "{{ homedir }}/Library/Application Support/Code"
  roles:
    - packages
    - dotfiles
    - desktop